//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caribou.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Caribou.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;osm version=&quot;0.6&quot; generator=&quot;Overpass API 0.7.56.1004 6cd3eaec&quot;&gt;
        ///&lt;note&gt;The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.&lt;/note&gt;
        ///&lt;meta osm_base=&quot;2020-07-23T08:46:02Z&quot;/&gt;
        ///
        ///  &lt;bounds minlat=&quot;-37.8164200&quot; minlon=&quot;144.9627400&quot; maxlat=&quot;-37.8089200&quot; maxlon=&quot;144.9710600&quot;/&gt;
        ///
        ///  &lt;node id=&quot;21579127&quot; lat=&quot;-37.8142176&quot; lon=&quot;144.9631608&quot; version=&quot;47&quot; timestamp=&quot;2019-04-26T11:53:45Z&quot; changeset=&quot;69597039&quot; uid=&quot;158784&quot; user=&quot;bjankul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MelbourneOSM {
            get {
                return ResourceManager.GetString("MelbourneOSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Students&gt;
        /// &lt;Student&gt;
        ///    &lt;Id&gt;Olivia&lt;/Id&gt;
        ///    &lt;Grade&gt;A&lt;/Grade&gt;
        ///  &lt;/Student&gt;
        ///  &lt;Student&gt;
        ///    &lt;Id&gt;Laura&lt;/Id&gt;
        ///    &lt;Grade&gt;A+&lt;/Grade&gt;
        ///  &lt;/Student&gt;
        ///  &lt;Student&gt;
        ///    &lt;Id&gt;Ben&lt;/Id&gt;
        ///    &lt;Grade&gt;A-&lt;/Grade&gt;
        ///  &lt;/Student&gt;
        ///  &lt;Student&gt;
        ///    &lt;Id&gt;&lt;/Id&gt;
        ///    &lt;Grade&gt;A-&lt;/Grade&gt;
        ///  &lt;/Student&gt;
        ///&lt;/Students&gt;
        ///.
        /// </summary>
        internal static string SimpleXMLParse {
            get {
                return ResourceManager.GetString("SimpleXMLParse", resourceCulture);
            }
        }
    }
}
